/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author tiennguyen
 */
public class chinhsuamonann extends javax.swing.JFrame {

    /**
     * Creates new form chinhsuamonann
     */
    public chinhsuamonann() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tenmon = new javax.swing.JTextField();
        giatien = new javax.swing.JTextField();
        save = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        trangthai = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        loai = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        id = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel6.setForeground(new java.awt.Color(0, 27, 72));
        jLabel6.setText("Đơn vị tính");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 72));
        jLabel1.setText("Chỉnh sửa món ăn");

        tenmon.setForeground(new java.awt.Color(0, 27, 72));

        giatien.setForeground(new java.awt.Color(0, 27, 72));
        giatien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                giatienActionPerformed(evt);
            }
        });

        save.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        save.setForeground(new java.awt.Color(0, 27, 72));
        save.setText("LƯU");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 27, 72));
        jLabel3.setText("Tên món");

        cancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 27, 72));
        cancel.setText("ĐÓNG");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(0, 27, 72));
        jLabel5.setText("Giá tiền");

        trangthai.setText("Trạng thái");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đang hoạt động", "Đã ngưng" }));

        loai.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đĩa", "Chai" }));

        jLabel2.setText("Loại");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Đồ ăn", "Nước uống" }));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        id.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(trangthai))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(giatien)
                            .addComponent(tenmon)
                            .addComponent(jComboBox1, 0, 246, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(save, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(id)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenmon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(giatien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(trangthai))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(save))
                .addGap(17, 17, 17)
                .addComponent(id))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
        boolean ktts=false;
        if (jLabel1.getText().equals("Thêm món ăn")) { 
                    //JOptionPane.showMessageDialog(this, "OKEt");
                ktts=true;
        } 
        try {
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();
            if (conn != null) {
                System.out.println("Connected");
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                String sql1 = "select * from MONAN where tenMonAn='" + tenmon.getText() + "'";
                ResultSet rs;
                rs = statement.executeQuery(sql1);
                if (tenmon.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập tên món ăn !!!");
                } else if (rs.next() && ktts==true) {
                    JOptionPane.showMessageDialog(this, "Tên món ăn đã bị trùng !!!");
                } else if (giatien.getText().equals("")) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập giá tiền !!!");
                }else 
                {
                    //JOptionPane.showMessageDialog(this, "oke");
                    String donvitinh = null;
                    int trangthai;
                    boolean l = false;
                    if(ktts == true)
                    {
            //them
                        
                        if(jComboBox1.getSelectedIndex()==0)
                        {
                            trangthai=1;
                        }else trangthai=0;
                        donvitinh="";
                        
                        if(loai.getSelectedIndex()==0)
                        {
                            donvitinh="Đĩa";
                        }else donvitinh="Chai";
                        
                        if(jComboBox3.getSelectedIndex()==0)
                        {
                            l=false;
                        }else l=true;
                                
                        String sqlthem=" insert into MONAN (tenMonAn,donvitinh,loai,gia,trangthai) values (N'" + tenmon.getText() + "',N'" + donvitinh + "','" + l + "',N'" + Integer.parseInt(giatien.getText()) + "',N'" + trangthai + "')";
                        boolean ktalterthem;
                        ktalterthem=statement.execute(sqlthem);
                        if(ktalterthem==false)
                        {
                            JOptionPane.showMessageDialog(this,"Thêm thành công !!!");
                            quanlimonan.loadTable();
                            this.dispose();
                        }
                    }else 
                    {
                        //System.out.println(jComboBox1.getSelectedIndex());
                        if(jComboBox1.getSelectedIndex()==0)
                        {
                            trangthai=1;
                        }else trangthai=0;
                        donvitinh="";
                        if(loai.getSelectedIndex()==0)
                        {
                            donvitinh="Đĩa";
                        }else donvitinh="Chai";
                        
                        if(jComboBox3.getSelectedIndex()==0)
                        {
                            l=false;
                        }else l=true;
            //sua
                        int soid = Integer.parseInt(id.getText());
                        int cosst=0;
                        cosst = Integer.parseInt(giatien.getText());
                        String sqlsua="update MONAn " 
					+ "set tenMonAn = N'" + tenmon.getText() + "'"
					+ ",donvitinh = '" + donvitinh + "'"
					+ ",loai = '" + l + "'"
                                        + ",gia = '" + cosst + "'"
                                        + ",trangthai = '" + trangthai + "'"
					+ "where idMonAn = '" + soid + "'";
                        boolean checksua;
                        checksua=statement.execute(sqlsua);
                        if(checksua==false)
                        {
                            JOptionPane.showMessageDialog(this, "Đã lưu");
                            quanlimonan.loadTable();
                            this.dispose();
                        }else JOptionPane.showMessageDialog(this, "Thất bại !!!");
                        
                    }
                }
                
            }
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }


    }//GEN-LAST:event_saveActionPerformed
public void setID(int str)
{
    id.setText(String.valueOf(str));
}
public void hideID()
{
    id.setVisible(false);
}
    private void giatienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_giatienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_giatienActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed
    public void setjlabel1(String str) {
        jLabel1.setText(str);
    }
    
    public void setloai(int i)
    {
        loai.setSelectedIndex(i);
    }
    public void setjcombobox3(int i)
    {
        jComboBox3.setSelectedIndex(i);
    }
    public void settrangthai(int i) {
        jComboBox1.setSelectedIndex(i);
    }

    public void settemon(String str) {
        tenmon.setText(str);
    }

  

    public void setgiatien(String str) {
        giatien.setText(str);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(chinhsuamonann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(chinhsuamonann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(chinhsuamonann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(chinhsuamonann.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new chinhsuamonann().setVisible(true);
                chinhsuamonann n = new chinhsuamonann();
                n.setVisible(true);
                n.setLocationRelativeTo(null);
                n.hideID();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField giatien;
    private javax.swing.JLabel id;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox loai;
    private javax.swing.JButton save;
    private javax.swing.JTextField tenmon;
    private javax.swing.JLabel trangthai;
    // End of variables declaration//GEN-END:variables
}
