/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import com.sun.rowset.CachedRowSetImpl;
import com.sun.rowset.JoinRowSetImpl;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.naming.spi.DirStateFactory.Result;
import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.JoinRowSet;
import javax.swing.JOptionPane;
import tkgd.order;
import cnpm.menuquantri;

/**
 *
 * @author tiennguyen
 */
public class dangnhap extends javax.swing.JFrame {

    /**
     * Creates new form dangnhap
     */
    public dangnhap() {
        initComponents();
    }
    void settexttk(String s)
    {
        txtf_username.setText(s);
    }
    void settextmk(String s)
    {
        txtf_pwd.setText(s);
    }
    String gettexttk() {
        String str = txtf_username.getText();
        return str;
    }

    String gettextmk() {
        String str = txtf_pwd.getText();
        return str;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_login = new javax.swing.JButton();
        txtf_username = new javax.swing.JTextField();
        btn_forget = new javax.swing.JButton();
        txtf_pwd = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Đăng nhập");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 72));
        jLabel1.setText("Tên người dùng");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 27, 72));
        jLabel2.setText("Mật khẩu");

        btn_login.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_login.setForeground(new java.awt.Color(0, 27, 72));
        btn_login.setText("Đăng nhập");
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });

        txtf_username.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        txtf_username.setForeground(new java.awt.Color(0, 27, 72));

        btn_forget.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        btn_forget.setForeground(new java.awt.Color(0, 27, 72));
        btn_forget.setText("Quên mật khẩu ? ");
        btn_forget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_forgetActionPerformed(evt);
            }
        });

        txtf_pwd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtf_pwdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btn_forget)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtf_username)
                            .addComponent(txtf_pwd))))
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtf_username, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtf_pwd))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_forget, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_login, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_forgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_forgetActionPerformed
        ForgetPassword fg=new ForgetPassword();
        fg.setVisible(true);
        fg.setLocationRelativeTo(null);
        fg.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btn_forgetActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        // TODO add your handling code here:
        String tk, mk;
        tk = gettexttk();
        mk = gettextmk();
        if (tk.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng điền tài khoản !!!");
        } else if (mk.equals("")) {
            JOptionPane.showConfirmDialog(this, "Vui lòng điền mật khẩu !!!");
        } else {
            try {
                String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
                Connection conn = DriverManager.getConnection(dbURL);
                Statement statement = conn.createStatement();
                boolean checkdn=false;
                if (conn != null) {
                    //System.out.println("Connected");
                    DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                    String sql1 = "select * from ACCOUNT";
                    ResultSet rs;
                    rs = statement.executeQuery(sql1);
                    String str1, str2;
                    int level,idNV;
                    while (rs.next()) {
                        str1 = rs.getString("username");
                        str2 = rs.getString("pwd");
                        level =rs.getInt("permission_level");
                        idNV = rs.getInt("owner");
                        if (str1.equals(tk) && str2.equals(mk)) {
                        //check user level
                            if(level == 1)
                            {
                                tk="Hello quản lí: "+tk;
                                menuquantri t = new menuquantri();
                                t.setLocationRelativeTo(null);
                                t.setVisible(true);
                                t.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
                                t.sethello(tk);
                                //get id of owner
                                t.setidNV(idNV);
                                this.dispose();
                                checkdn=true;
                                break;
                               
                            }else 
                            {
                                order z=new order();
                                z.setLocationRelativeTo(null);
                                z.setVisible(true);
                                if(level==2)
                                {
                                    tk="Thu ngân: "+tk;
                                }else tk="Nhân viên: "+tk;
                                z.settennguoidung(tk);
                            //GET id owner
                                z.setidNV(idNV);
                                this.dispose();
                                checkdn=true;
                                break;
                            }
                        }
                    }
                    if(checkdn==false){
                            //System.out.println("no");
                            JOptionPane.showMessageDialog(this, "Sai tài khoản hoặc mặt khẩu !!!");
                            settextmk("");
                            settexttk("");
                            
                        }
                }
                conn.close();
            } catch (SQLException ex) {
                System.err.println("Cannot connect database, " + ex);
            }
        }
    }//GEN-LAST:event_btn_loginActionPerformed

    private void txtf_pwdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtf_pwdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtf_pwdActionPerformed

    /**
     * @throws java.sql.SQLException
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dangnhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dangnhap().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_forget;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField txtf_pwd;
    private javax.swing.JTextField txtf_username;
    // End of variables declaration//GEN-END:variables
}
