/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import tkgd.order;

/**
 *
 * @author tiennguyen
 */
public class menuquantri extends javax.swing.JFrame {
    int idNV;
    /**
     * Creates new form menuquantri
     */
    public void setidNV(int i){
        this.idNV=i;
    }
    public menuquantri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btntaikhoan = new javax.swing.JButton();
        btn_qlnguyenlieu = new javax.swing.JButton();
        btn_pthu = new javax.swing.JButton();
        btn_pchi = new javax.swing.JButton();
        btn_ncc = new javax.swing.JButton();
        btnbanhang = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btndoanhthu = new javax.swing.JButton();
        btnnhanvien = new javax.swing.JButton();
        btn_hoadon = new javax.swing.JButton();
        btndangxuat = new javax.swing.JButton();
        btn_qlmonan = new javax.swing.JButton();
        hello = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntaikhoan.setBackground(new java.awt.Color(2, 69, 122));
        btntaikhoan.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btntaikhoan.setForeground(new java.awt.Color(255, 255, 255));
        btntaikhoan.setText("TÀI KHOẢN");
        btntaikhoan.setBorder(null);
        btntaikhoan.setBorderPainted(false);
        btntaikhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaikhoanActionPerformed(evt);
            }
        });

        btn_qlnguyenlieu.setBackground(new java.awt.Color(102, 102, 255));
        btn_qlnguyenlieu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_qlnguyenlieu.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlnguyenlieu.setText("QUẢN LÝ NGUYÊN LIỆU");
        btn_qlnguyenlieu.setBorder(null);
        btn_qlnguyenlieu.setBorderPainted(false);
        btn_qlnguyenlieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlnguyenlieuActionPerformed(evt);
            }
        });

        btn_pthu.setBackground(new java.awt.Color(2, 69, 122));
        btn_pthu.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_pthu.setForeground(new java.awt.Color(255, 255, 255));
        btn_pthu.setText("PHIẾU THU");
        btn_pthu.setBorder(null);
        btn_pthu.setBorderPainted(false);
        btn_pthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pthuActionPerformed(evt);
            }
        });

        btn_pchi.setBackground(new java.awt.Color(2, 69, 122));
        btn_pchi.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_pchi.setForeground(new java.awt.Color(255, 255, 255));
        btn_pchi.setText("PHIẾU CHI");
        btn_pchi.setBorder(null);
        btn_pchi.setBorderPainted(false);
        btn_pchi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pchiActionPerformed(evt);
            }
        });

        btn_ncc.setBackground(new java.awt.Color(2, 69, 122));
        btn_ncc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btn_ncc.setForeground(new java.awt.Color(255, 255, 255));
        btn_ncc.setText("NHÀ CUNG CẤP");
        btn_ncc.setBorder(null);
        btn_ncc.setBorderPainted(false);
        btn_ncc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nccActionPerformed(evt);
            }
        });

        btnbanhang.setBackground(new java.awt.Color(41, 29, 137));
        btnbanhang.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnbanhang.setForeground(new java.awt.Color(255, 255, 255));
        btnbanhang.setText("   BÁN HÀNG");
        btnbanhang.setBorder(null);
        btnbanhang.setBorderPainted(false);
        btnbanhang.setPreferredSize(new java.awt.Dimension(430, 250));
        btnbanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbanhangActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 72));
        jLabel1.setText("QUẢN TRỊ");

        btndoanhthu.setBackground(new java.awt.Color(78, 103, 235));
        btndoanhthu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btndoanhthu.setForeground(new java.awt.Color(255, 255, 255));
        btndoanhthu.setText("   QUẢN LÝ DOANH THU");
        btndoanhthu.setBorder(null);
        btndoanhthu.setBorderPainted(false);
        btndoanhthu.setPreferredSize(new java.awt.Dimension(430, 250));
        btndoanhthu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndoanhthuActionPerformed(evt);
            }
        });

        btnnhanvien.setBackground(new java.awt.Color(214, 235, 238));
        btnnhanvien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnnhanvien.setForeground(new java.awt.Color(41, 29, 137));
        btnnhanvien.setText("   QUẢN LÝ NHÂN VIÊN");
        btnnhanvien.setBorder(null);
        btnnhanvien.setBorderPainted(false);
        btnnhanvien.setPreferredSize(new java.awt.Dimension(430, 250));
        btnnhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnhanvienActionPerformed(evt);
            }
        });

        btn_hoadon.setBackground(new java.awt.Color(151, 202, 219));
        btn_hoadon.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_hoadon.setForeground(new java.awt.Color(41, 29, 137));
        btn_hoadon.setText("   QUẢN LÝ HÓA ĐƠN");
        btn_hoadon.setBorder(null);
        btn_hoadon.setBorderPainted(false);
        btn_hoadon.setPreferredSize(new java.awt.Dimension(430, 250));
        btn_hoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hoadonActionPerformed(evt);
            }
        });

        btndangxuat.setBackground(new java.awt.Color(0, 27, 72));
        btndangxuat.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btndangxuat.setForeground(new java.awt.Color(255, 255, 255));
        btndangxuat.setText("  ĐĂNG XUẤT");
        btndangxuat.setBorder(null);
        btndangxuat.setBorderPainted(false);
        btndangxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndangxuatActionPerformed(evt);
            }
        });

        btn_qlmonan.setBackground(new java.awt.Color(2, 69, 122));
        btn_qlmonan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btn_qlmonan.setForeground(new java.awt.Color(255, 255, 255));
        btn_qlmonan.setText("QUẢN LÝ THỰC ĐƠN");
        btn_qlmonan.setBorder(null);
        btn_qlmonan.setBorderPainted(false);
        btn_qlmonan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_qlmonanActionPerformed(evt);
            }
        });

        hello.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        hello.setForeground(new java.awt.Color(0, 27, 72));
        hello.setText("HELLO QUẢN LÍ ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btndoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_qlmonan, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btn_qlnguyenlieu, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE))
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_pthu, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btntaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_pchi, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(397, 397, 397)
                        .addComponent(hello, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_qlnguyenlieu, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_qlmonan, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_hoadon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(110, 110, 110))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(hello)
                                .addGap(49, 49, 49)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnbanhang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btndoanhthu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnnhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addComponent(btntaikhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_pthu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_pchi, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ncc, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 142, Short.MAX_VALUE)
                        .addComponent(btndangxuat, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbanhangActionPerformed
        // TODO add your handling code here:
        order z = new order();
        String name= gethello();
        String [] output= name.split(":");
        name=output[1];
        z.setVisible(true);
        z.settennguoidung("Quản lí : "+name);
        z.setidNV(idNV);
        z.setLocationRelativeTo(null);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnbanhangActionPerformed

    private void btn_hoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hoadonActionPerformed
        HOADON z = null;
        try {
            z = new HOADON();
        } catch (SQLException ex) {
            Logger.getLogger(menuquantri.class.getName()).log(Level.SEVERE, null, ex);
        }
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_hoadonActionPerformed

    private void btndoanhthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndoanhthuActionPerformed
        THONGKE z = new THONGKE();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btndoanhthuActionPerformed

    private void btnnhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnhanvienActionPerformed
        // TODO add your handling code here:
        quanlynhanvien z = new quanlynhanvien();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnnhanvienActionPerformed

    private void btn_qlmonanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlmonanActionPerformed
        // TODO add your handling code here:
        quanlimonan z = new quanlimonan();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_qlmonanActionPerformed

    private void btn_qlnguyenlieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_qlnguyenlieuActionPerformed
        NGUYENLIEU z = new NGUYENLIEU();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_qlnguyenlieuActionPerformed

    private void btntaikhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaikhoanActionPerformed
        // TODO add your handling code here:
        quanlitaikhoannhanvien z = new quanlitaikhoannhanvien();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btntaikhoanActionPerformed

    private void btndangxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndangxuatActionPerformed
        // TODO add your handling code here:
        this.dispose();
        dangnhap z = new dangnhap();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btndangxuatActionPerformed

    private void btn_pthuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pthuActionPerformed
        PHIEUTHU z = new PHIEUTHU();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_pthuActionPerformed

    private void btn_pchiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pchiActionPerformed
        PHIEUCHI z = new PHIEUCHI();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_pchiActionPerformed

    private void btn_nccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nccActionPerformed
        NCC z=new NCC();
        z.setVisible(true);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        z.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_nccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menuquantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menuquantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menuquantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menuquantri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menuquantri().setVisible(true);
            }
        });
    }
    public void sethello(String str)
    {
        hello.setText(str);
    }
    public String gethello()
    {
        return hello.getText();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hoadon;
    private javax.swing.JButton btn_ncc;
    private javax.swing.JButton btn_pchi;
    private javax.swing.JButton btn_pthu;
    private javax.swing.JButton btn_qlmonan;
    private javax.swing.JButton btn_qlnguyenlieu;
    private javax.swing.JButton btnbanhang;
    private javax.swing.JButton btndangxuat;
    private javax.swing.JButton btndoanhthu;
    private javax.swing.JButton btnnhanvien;
    private javax.swing.JButton btntaikhoan;
    private javax.swing.JLabel hello;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
