/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

/**
 *
 * @author emipham
 */
public class qlyhoadon extends javax.swing.JFrame {

    /**
     * Creates new form qlyhoadon
     */
    public qlyhoadon() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        bangchitietdon = new javax.swing.JTable();
        btnnext = new javax.swing.JButton();
        btnprevious = new javax.swing.JButton();
        btnIn = new javax.swing.JToggleButton();
        btnloc = new javax.swing.JToggleButton();
        labelquanly = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listdonhang = new javax.swing.JTable();
        labeldanhsach = new javax.swing.JLabel();
        labelchitiet = new javax.swing.JLabel();
        labelmadon = new javax.swing.JLabel();
        searchmadon = new javax.swing.JTextField();
        labeltungay = new javax.swing.JLabel();
        labeldenngay = new javax.swing.JLabel();
        tungay = new javax.swing.JComboBox<>();
        denngay = new javax.swing.JComboBox<>();
        btnuathich = new javax.swing.JToggleButton();
        btntim = new javax.swing.JToggleButton();
        labelmadon1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 255));
        setPreferredSize(new java.awt.Dimension(1228, 660));

        bangchitietdon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "STT", "    TÊN MÓN", "ĐƠN GIÁ", "SL", "GIẢM GIÁ"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        bangchitietdon.setRowHeight(20);
        bangchitietdon.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(bangchitietdon);
        if (bangchitietdon.getColumnModel().getColumnCount() > 0) {
            bangchitietdon.getColumnModel().getColumn(0).setMinWidth(30);
            bangchitietdon.getColumnModel().getColumn(0).setMaxWidth(30);
            bangchitietdon.getColumnModel().getColumn(0).setHeaderValue("STT");
            bangchitietdon.getColumnModel().getColumn(1).setMinWidth(200);
            bangchitietdon.getColumnModel().getColumn(1).setMaxWidth(200);
            bangchitietdon.getColumnModel().getColumn(1).setHeaderValue("    TÊN MÓN");
            bangchitietdon.getColumnModel().getColumn(2).setHeaderValue("ĐƠN GIÁ");
            bangchitietdon.getColumnModel().getColumn(3).setMinWidth(40);
            bangchitietdon.getColumnModel().getColumn(3).setMaxWidth(40);
            bangchitietdon.getColumnModel().getColumn(3).setHeaderValue("SL");
            bangchitietdon.getColumnModel().getColumn(4).setMinWidth(80);
            bangchitietdon.getColumnModel().getColumn(4).setMaxWidth(100);
            bangchitietdon.getColumnModel().getColumn(4).setHeaderValue("GIẢM GIÁ");
        }

        btnnext.setBackground(new java.awt.Color(204, 204, 255));
        btnnext.setBorder(null);
        btnnext.setBorderPainted(false);

        btnprevious.setBackground(new java.awt.Color(204, 204, 255));
        btnprevious.setBorder(null);
        btnprevious.setBorderPainted(false);
        btnprevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpreviousActionPerformed(evt);
            }
        });

        btnIn.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIn.setForeground(new java.awt.Color(0, 27, 72));
        btnIn.setText("IN LẠI");
        btnIn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));

        btnloc.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnloc.setForeground(new java.awt.Color(0, 27, 72));
        btnloc.setText("LỌC");
        btnloc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));

        labelquanly.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelquanly.setForeground(new java.awt.Color(0, 27, 72));
        labelquanly.setText("QUẢN LÝ HÓA ĐƠN");
        labelquanly.setAlignmentX(0.5F);
        labelquanly.setAutoscrolls(true);
        labelquanly.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));

        listdonhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "MÃ ĐƠN", "KHÁCH HÀNG", "GIỜ", "MÃ GIẢM GIÁ", "% GIẢM", "THÀNH TIỀN"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listdonhang.setRowHeight(22);
        listdonhang.setRowMargin(2);
        listdonhang.setRowSelectionAllowed(false);
        listdonhang.setSelectionBackground(new java.awt.Color(204, 204, 255));
        listdonhang.setSelectionForeground(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(listdonhang);
        if (listdonhang.getColumnModel().getColumnCount() > 0) {
            listdonhang.getColumnModel().getColumn(0).setMinWidth(90);
            listdonhang.getColumnModel().getColumn(0).setMaxWidth(90);
            listdonhang.getColumnModel().getColumn(2).setMinWidth(70);
            listdonhang.getColumnModel().getColumn(2).setMaxWidth(70);
        }

        labeldanhsach.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labeldanhsach.setText("Danh sách hóa đơn");

        labelchitiet.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        labelchitiet.setText("Chi tiết hóa đơn");

        labelmadon.setForeground(new java.awt.Color(0, 27, 72));
        labelmadon.setText("Tìm kiếm theo mã hóa đơn");

        searchmadon.setForeground(new java.awt.Color(0, 27, 72));
        searchmadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchmadonActionPerformed(evt);
            }
        });

        labeltungay.setForeground(new java.awt.Color(0, 27, 72));
        labeltungay.setText("Từ ngày");

        labeldenngay.setForeground(new java.awt.Color(0, 27, 72));
        labeldenngay.setText("Đến ngày");

        tungay.setForeground(new java.awt.Color(0, 27, 72));
        tungay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        denngay.setForeground(new java.awt.Color(0, 27, 72));
        denngay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnuathich.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnuathich.setForeground(new java.awt.Color(0, 27, 72));
        btnuathich.setText("DANH SÁCHMÓN ƯA THÍCH");
        btnuathich.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));

        btntim.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btntim.setForeground(new java.awt.Color(0, 27, 72));
        btntim.setText("TÌM");
        btntim.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));

        labelmadon1.setForeground(new java.awt.Color(0, 27, 72));
        labelmadon1.setText("Lọc theo ngày");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelquanly, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(labeltungay)
                                        .addGap(18, 18, 18)
                                        .addComponent(tungay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(labeldenngay)
                                        .addGap(18, 18, 18)
                                        .addComponent(denngay, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(labelmadon, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(searchmadon, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnloc, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btntim, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labeldanhsach, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelmadon1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelchitiet, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(51, 51, 51)
                                    .addComponent(btnuathich, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnprevious, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(17, 17, 17)
                                    .addComponent(btnnext))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 469, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelquanly, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnuathich, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnIn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(labelmadon1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(labeltungay)
                                    .addComponent(tungay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labeldenngay)
                                    .addComponent(denngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnloc, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelmadon)
                                .addComponent(btntim, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(searchmadon)))
                    .addComponent(btnnext)
                    .addComponent(btnprevious))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labeldanhsach)
                    .addComponent(labelchitiet))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnpreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpreviousActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnpreviousActionPerformed

    private void searchmadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchmadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchmadonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(qlyhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(qlyhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(qlyhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(qlyhoadon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new qlyhoadon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable bangchitietdon;
    private javax.swing.JToggleButton btnIn;
    private javax.swing.JToggleButton btnloc;
    private javax.swing.JButton btnnext;
    private javax.swing.JButton btnprevious;
    private javax.swing.JToggleButton btntim;
    private javax.swing.JToggleButton btnuathich;
    private javax.swing.JComboBox<String> denngay;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelchitiet;
    private javax.swing.JLabel labeldanhsach;
    private javax.swing.JLabel labeldenngay;
    private javax.swing.JLabel labelmadon;
    private javax.swing.JLabel labelmadon1;
    private javax.swing.JLabel labelquanly;
    private javax.swing.JLabel labeltungay;
    private javax.swing.JTable listdonhang;
    private javax.swing.JTextField searchmadon;
    private javax.swing.JComboBox<String> tungay;
    // End of variables declaration//GEN-END:variables
}
