/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import cnpm.chinhsuamonann;
/**
 *
 * @author tiennguyen
 */
public class quanlimonan extends javax.swing.JFrame {

    /**
     * Creates new form quanlimonan
     */
    public quanlimonan() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_add_mon_an = new javax.swing.JButton();
        btnsua_monan = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_add_mon_an.setForeground(new java.awt.Color(0, 27, 72));
        btn_add_mon_an.setText("Thêm món ăn");
        btn_add_mon_an.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));
        btn_add_mon_an.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_mon_anActionPerformed(evt);
            }
        });

        btnsua_monan.setForeground(new java.awt.Color(0, 27, 72));
        btnsua_monan.setText("Sửa thông tin");
        btnsua_monan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 27, 72)));
        btnsua_monan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsua_monanActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 27, 72));
        jLabel2.setText("QUẢN LÝ MÓN ĂN");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã món ăn", "Tên món", "Loại", "Đơn vị tính", "Giá"
            }
        ));
        jTable1.setRowHeight(20);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(1).setMinWidth(300);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(300);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(300);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_add_mon_an, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnsua_monan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_add_mon_an, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsua_monan, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_add_mon_anActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_mon_anActionPerformed
        chinhsuamonann z = new chinhsuamonann();
        z.setjlabel1("Thêm món ăn");
        z.setTitle("");
        //z.setTextButton("Thêm");
        //z.setTextJlabel5("Thêm tài khoản");
        z.setLocationRelativeTo(null);
        z.setVisible(true);
        z.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
        z.hideID();
        loadTable();
    }//GEN-LAST:event_btn_add_mon_anActionPerformed

    private void btnsua_monanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsua_monanActionPerformed
        // TODO add your handling code here:
        int i;
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel(); 
        i=jTable1.getSelectedRow();
        
        //System.out.println("giá trị rów"+i+" ");
        if(i>=0)
        {
            chinhsuamonann z = new chinhsuamonann();
            z.setjlabel1("Sửa món ăn");
            z.setLocationRelativeTo(null);
            z.setVisible(true);
            z.setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
            
            
            z.settemon((String) model.getValueAt(i, 1));
            
            String loaimonannnn=(String) model.getValueAt(i,2);
            if(loaimonannnn.equals("Đĩa"))
            {
                z.setloai(0);
            }
            else z.setloai(1);
            String hhh=(String) model.getValueAt(i,3);
            if(hhh.equals("Đồ ăn"))
            {
                z.setjcombobox3(0);
            }
            else z.setjcombobox3(1);
            
            
            int a=(int) model.getValueAt(i, 4);
            z.setgiatien(String.valueOf(a));
            
            int xyz=(int) model.getValueAt(i, 0);
            z.setID(xyz);
            z.hideID();
            
            String b = (String) model.getValueAt(i, 5);
            if(b.equals("Đang hoạt động"))
            {
                z.settrangthai(0);
            }  else z.settrangthai(1);
          
//            try {
//                String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
//                Connection conn = DriverManager.getConnection(dbURL);
//                Statement statement = conn.createStatement();
//                if (conn != null) {
//                    System.out.println("Connected");
//                    DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
//                    String sql1 = "select * from NHANVIEN where idNV=" + model.getValueAt(i, 2);
//                    ResultSet rs;
//                    rs = statement.executeQuery(sql1);
//                    String ten = "";
//                    while (rs.next()) {
//                        ten = rs.getString("tenNV");
//                    }
//                    z.setTextJTextfiel1(ten);
//                }
//            } catch (SQLException ex) {
//                System.err.println("Cannot connect database, " + ex);
//            }
            // 
            //model.removeRow(i);
            loadTable();
        }else
        {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn món ăn cần sửa !!!");
        }
    }//GEN-LAST:event_btnsua_monanActionPerformed
    public static void loadTable() {
        try {
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();

            Object[] columm = {"Mã món ăn", "Tên món ăn", "Đơn vị tính", "Loai", "Giá","Trạng thái"};
            DefaultTableModel model = new DefaultTableModel();
            //model = (DefaultTableModel) bangdanhsachtk.getModel();
            model.setColumnIdentifiers(columm);
            jTable1.setModel(model);
            if (conn != null) {
                System.out.println("Connected");
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                String sql1 = "select * from MONAN";
                ResultSet rs;
                rs = statement.executeQuery(sql1);
                Object[] rows = new Object[10];
                while (rs.next()) {
                    rows[0] = rs.getInt("idMonAn");
                    //System.out.println(rows[0]);
                    rows[1] = rs.getString("tenMonAn");
                    //System.out.println(rows[2]);
                    rows[2] = rs.getString("donvitinh");
                    
                    
                    int kl =rs.getInt("loai");
                    if(kl==0)
                    {
                        rows[3]="Đồ ăn";
                    }else rows[3]="Nước uống";
                    
                    rows[4] = rs.getInt("gia");
                    int yy=rs.getInt("trangthai");
                    if(yy==1)
                    {
                        rows[5] = "Đang hoạt động";
                    }else 
                    {
                        rows[5] = "Đã ngưng";
                    }
                   
                    //System.out.println(rows[1]);
                    model.addRow(rows);
                }
            }
            conn.close();
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlimonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlimonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlimonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlimonan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quanlimonan z = new quanlimonan();
                z.setLocationRelativeTo(null);
                z.loadTable();
                z.setVisible(true);
                z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_add_mon_an;
    private javax.swing.JButton btnsua_monan;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
