/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author emipham
 */
public class quanlynhanvien extends javax.swing.JFrame {

    /**
     * Creates new form quanlynhanvien
     */
    public quanlynhanvien() {
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnsuanv = new javax.swing.JButton();
        searchnv = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        aDD = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btn_search = new javax.swing.JButton();
        menuquanlynv = new javax.swing.JMenuBar();
        danhsachnv = new javax.swing.JMenu();
        bangluong = new javax.swing.JMenu();
        parttime = new javax.swing.JMenuItem();
        fulltime = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã NV", "Tên nhân viên", "Loại", "Chức vụ", "Lương", "Ngày vào làm", "Số điện thoại", "Ngày sinh", "Giới tính", "Địa chỉ", "Số CMND"
            }
        ));
        jTable1.setName(""); // NOI18N
        jTable1.setRowHeight(22);
        jTable1.setSelectionBackground(new java.awt.Color(204, 204, 255));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(50);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(50);
            jTable1.getColumnModel().getColumn(1).setMinWidth(200);
            jTable1.getColumnModel().getColumn(1).setMaxWidth(200);
            jTable1.getColumnModel().getColumn(2).setMinWidth(70);
            jTable1.getColumnModel().getColumn(2).setMaxWidth(70);
            jTable1.getColumnModel().getColumn(3).setMinWidth(60);
            jTable1.getColumnModel().getColumn(3).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(4).setMinWidth(100);
            jTable1.getColumnModel().getColumn(4).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(5).setMinWidth(100);
            jTable1.getColumnModel().getColumn(5).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(6).setMinWidth(100);
            jTable1.getColumnModel().getColumn(6).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(7).setMinWidth(100);
            jTable1.getColumnModel().getColumn(7).setMaxWidth(100);
            jTable1.getColumnModel().getColumn(8).setMinWidth(60);
            jTable1.getColumnModel().getColumn(8).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(10).setMinWidth(150);
            jTable1.getColumnModel().getColumn(10).setMaxWidth(150);
        }

        btnsuanv.setForeground(new java.awt.Color(0, 27, 72));
        btnsuanv.setText("Sửa thông tin");
        btnsuanv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuanvActionPerformed(evt);
            }
        });

        searchnv.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchnvKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 27, 72));
        jLabel1.setText("Danh sách nhân viên");

        aDD.setText("Thêm nhân viên");
        aDD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aDDActionPerformed(evt);
            }
        });

        jLabel2.setText("Tìm kiếm");

        btn_search.setText("Tìm");

        menuquanlynv.setForeground(new java.awt.Color(0, 27, 72));
        menuquanlynv.setMargin(new java.awt.Insets(15, 0, 0, 0));
        menuquanlynv.setName(""); // NOI18N
        menuquanlynv.setPreferredSize(new java.awt.Dimension(192, 30));

        danhsachnv.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        danhsachnv.setText("Danh sách nhân viên");
        menuquanlynv.add(danhsachnv);

        bangluong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        bangluong.setText("Bảng lương");
        bangluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bangluongActionPerformed(evt);
            }
        });

        parttime.setText("Part time");
        parttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parttimeActionPerformed(evt);
            }
        });
        bangluong.add(parttime);

        fulltime.setText("Full time");
        fulltime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fulltimeActionPerformed(evt);
            }
        });
        bangluong.add(fulltime);

        menuquanlynv.add(bangluong);

        setJMenuBar(menuquanlynv);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1213, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchnv, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_search)
                        .addGap(1, 1, 1)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnsuanv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(aDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(aDD, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnsuanv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(searchnv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_search))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

//        try {
//            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
//            Connection conn = DriverManager.getConnection(dbURL);
//            Statement statement = conn.createStatement();
//            if (conn != null) {
//                System.out.println("Connected");
//                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
//                //String sqlUpdate = "UPDATE NHANVIEN SET DIACHI = 'Hanoi', LUONG = 10000.00;";
//                // xét tài khoản ko dc trùng
//            }
//        } catch (SQLException ex) {
//            System.err.println("Cannot connect database, " + ex);
//    
public int getmanhanvien(String str) {
        int status = 0;
        try {
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();
            if (conn != null) {
                //System.out.println("Connected");
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                String sql = "select * from NHANVIEN where tenNV = N'" + str + "'";
                ResultSet rs;
                rs = statement.executeQuery(sql);

                while (rs.next()) {
                    status = rs.getInt("idNV");
                    break;
                }
            }
            conn.close();
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }
        return status;
    }
    private void btnsuanvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuanvActionPerformed
        // TODO add your handling code here:
        themmoinv tnv = new themmoinv();
        DefaultTableModel model = new DefaultTableModel();
        model = (DefaultTableModel) jTable1.getModel();
        int i = -1;
        i = jTable1.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn nhân viên muốn cập nhật !!!");
        } else {
            tnv.setTextmaNV(String.valueOf( getmanhanvien( (String) jTable1.getValueAt(i, 0) ) ));
            tnv.hidemaNV();
            tnv.setLocationRelativeTo(null);
            tnv.setVisible(true);
            tnv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            tnv.setTextjbtadd("Cập nhật");
            tnv.setTextjlabel8("Cập nhật nhân viên");
            tnv.setTextName((String) jTable1.getValueAt(i, 0));
            tnv.setTextSDT((String) jTable1.getValueAt(i, 5));
            tnv.setCMND((String) jTable1.getValueAt(i, 9));
            tnv.setLuong((String) jTable1.getValueAt(i, 3));
            tnv.setDiaChi((String) jTable1.getValueAt(i, 8));
            String loainv=(String) jTable1.getValueAt(i, 1);
            System.out.println(loainv);
            if(loainv.equals("FullTime"))
            {
                tnv.setCa(1);
            }else 
            {
                tnv.setCa(0);
            }
            //tnv.setCa((int) jTable1.getValueAt(i, 2));
            String chucvu =(String) jTable1.getValueAt(i, 2);
            System.out.println(chucvu);
            if(chucvu.equals("Phục vụ"))
            {
                tnv.setChucVu(0);
            }else if(chucvu.equals("Thu ngân")) 
            {
                tnv.setChucVu(2);
            }else 
            {
                tnv.setChucVu(1);
            }
            //tnv.setChucVu((int) jTable1.getValueAt(i, 3));
            String male = (String) jTable1.getValueAt(i, 7);
            if (male.equals("Nam")) {
                tnv.setGioiTinh(0);
            } else {
                tnv.setGioiTinh(1);
            }
//            DateFormat dateFormat = new SimpleDateFormat("dd-MM-yyyy");
//            String strDate = dateFormat.format(jTable1.getValueAt(i, 4));
            tnv.setNgaySinh((String) jTable1.getValueAt(i, 4));
         
            
        
            
            
            
        }
    }//GEN-LAST:event_btnsuanvActionPerformed

    private void aDDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aDDActionPerformed
        // TODO add your handling code here:
        themmoinv tnv = new themmoinv();
        tnv.setLocationRelativeTo(null);
        tnv.setVisible(true);
        tnv.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        try {
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();
            if (conn != null) {
                System.out.println("Connected");
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                //String sql = "select COUNT(*) AS count from NHANVIEN";
                int count = 0;
                ResultSet rs3 = statement.executeQuery("SELECT COUNT(*) AS count FROM NHANVIEN");
                while (rs3.next()) {
                    count = rs3.getInt("count");
                }

                tnv.setTextmaNV(String.valueOf(count + 1));
                tnv.hidemaNV();
                // xét tài khoản ko dc trùng
            }
            conn.close();
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }
    }//GEN-LAST:event_aDDActionPerformed

    private void searchnvKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchnvKeyReleased
        try {
            Object[] columm = {"Tên nhân viên", "Loại", "Chức vụ", "Lương", "Ngày vào làm", "SĐT", "Ngày sinh", "Giới tính", "Địa chỉ", "CMND"};
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(columm);
            jTable1.setModel(model);
            
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();
            if (conn != null) {
                System.out.println("Connected");
                //DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                Object[] rows = new Object[11];
                ResultSet rs3;
                String txt_search="SELECT * FROM NHANVIEN WHERE tenNV like N'%"+searchnv.getText()+"%' or tenNV like N'%"+searchnv.getText()+"%' or sdt like N'%"+searchnv.getText()+"%' or diachi like N'%"+searchnv.getText()+"%' or CMND like N'%"+searchnv.getText()+"%'";
                rs3= statement.executeQuery(txt_search);
                while (rs3.next()) {
                    rows[0] = rs3.getString("tenNV");
                    int loainv = rs3.getInt("loaiNV");
                    if (loainv == 1) {
                        rows[1] = "FullTime";
                    } else {
                        rows[1] = "PartTime";
                    }
                    rows[2] = rs3.getString("chucvu");
                    rows[3] = rs3.getString("luong");
                    rows[4] = rs3.getDate("ngayvaolam");
                    rows[5] = rs3.getString("sdt");
                    rows[6] = rs3.getDate("ngaysinh");
                    int sex = rs3.getInt("gioitinh");
                    if (sex == 1) {
                        rows[7] = "Nữ";
                    } else {
                        rows[7] = "Nam";
                    }
                    rows[8] = rs3.getString("diachi");
                    rows[9] = rs3.getString("CMND");

                    model.addRow(rows);
                }
            }
            conn.close();
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }
    }//GEN-LAST:event_searchnvKeyReleased

    private void bangluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bangluongActionPerformed
        // TODO add your handling code here:
        bangluongnhavienparttime z = new bangluongnhavienparttime();
        z.setVisible(true);
        z.setLocationRelativeTo(null);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_bangluongActionPerformed

    private void parttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parttimeActionPerformed
        // TODO add your handling code here:
        bangluongnhavienparttime z =new bangluongnhavienparttime();
        z.setVisible(true);
        z.setLocationRelativeTo(null);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_parttimeActionPerformed

    private void fulltimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fulltimeActionPerformed
        // TODO add your handling code here:
        bangluongnhanvienfulltime z = new bangluongnhanvienfulltime();
        z.setVisible(true);
        z.setLocationRelativeTo(null);
        z.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_fulltimeActionPerformed

    public static void loadTable() {
        try {
            String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
            Connection conn = DriverManager.getConnection(dbURL);
            Statement statement = conn.createStatement();

            Object[] columm = {"Tên nhân viên", "Loại", "Chức vụ", "Lương", "Ngày vào làm", "SĐT", "Ngày sinh", "Giới tính", "Địa chỉ", "CMND"};
            DefaultTableModel model = new DefaultTableModel();
            //model = (DefaultTableModel) bangdanhsachtk.getModel();
            model.setColumnIdentifiers(columm);
            jTable1.setModel(model);
            if (conn != null) {
                System.out.println("Connected");
                DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                String sql1 = "select * from NHANVIEN";
                ResultSet rs;
                rs = statement.executeQuery(sql1);
                Object[] rows = new Object[11];
                while (rs.next()) {
                    rows[0] = rs.getString("tenNV");
                    int loainv = rs.getInt("loaiNV");
                    if (loainv == 1) {
                        rows[1] = "FullTime";
                    } else {
                        rows[1] = "PartTime";
                    }
                    rows[2] = rs.getString("chucvu");
                    rows[3] = rs.getString("luong");
                    
                    Date getdate=rs.getDate("ngayvaolam");
                    String datetostring = String.valueOf(getdate);
                    String[] spilitstringdate = datetostring.split("-");
                    datetostring=spilitstringdate[2]+"/"+spilitstringdate[1]+"/"+spilitstringdate[0];
                    
                    
                    rows[4] = datetostring;
                    rows[5] = rs.getString("sdt");
                    
                    
                    getdate=rs.getDate("ngaysinh");
                    datetostring = String.valueOf(getdate);
                    spilitstringdate = datetostring.split("-");
                    datetostring=spilitstringdate[2]+"/"+spilitstringdate[1]+"/"+spilitstringdate[0];
                    
                    
                    rows[6] = datetostring;
                    int sex = rs.getInt("gioitinh");
                    if (sex == 1) {
                        rows[7] = "Nữ";
                    } else {
                        rows[7] = "Nam";
                    }
                    rows[8] = rs.getString("diachi");
                    rows[9] = rs.getString("CMND");

                    model.addRow(rows);
                }
            }
            conn.close();
        } catch (SQLException ex) {
            System.err.println("Cannot connect database, " + ex);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quanlynhanvien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                quanlynhanvien qlnv = new quanlynhanvien();
                qlnv.setLocationRelativeTo(null);
                qlnv.setVisible(true);
                //new quanlynhanvien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aDD;
    private javax.swing.JMenu bangluong;
    private javax.swing.JButton btn_search;
    private javax.swing.JButton btnsuanv;
    private javax.swing.JMenu danhsachnv;
    private javax.swing.JMenuItem fulltime;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTable1;
    private javax.swing.JMenuBar menuquanlynv;
    private javax.swing.JMenuItem parttime;
    private javax.swing.JTextField searchnv;
    // End of variables declaration//GEN-END:variables
}
