/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cnpm;

import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.text.DateFormatter;

/**
 *
 * @author tiennguyen
 */
public class themmoinv extends javax.swing.JFrame {

    /**
     * Creates new form themmoinv
     */
    public themmoinv() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tenNV = new javax.swing.JTextField();
        cancel = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        luong = new javax.swing.JTextField();
        sdtNV = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        add = new javax.swing.JButton();
        maNV = new javax.swing.JTextField();
        soCMND = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        diachi = new javax.swing.JTextArea();
        gioitinh = new javax.swing.JComboBox();
        ngaysinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ChucVu = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Ca = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setForeground(new java.awt.Color(0, 27, 72));
        jLabel2.setText("Địa chỉ");

        jLabel1.setForeground(new java.awt.Color(0, 27, 72));
        jLabel1.setText("SĐT");

        tenNV.setForeground(new java.awt.Color(0, 27, 72));

        cancel.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        cancel.setForeground(new java.awt.Color(0, 27, 72));
        cancel.setText("Đóng");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 27, 72));
        jLabel3.setText("Tên NV");

        jLabel4.setForeground(new java.awt.Color(0, 27, 72));
        jLabel4.setText("Mã NV");

        jLabel7.setForeground(new java.awt.Color(0, 27, 72));
        jLabel7.setText("Giới tính");

        luong.setForeground(new java.awt.Color(0, 27, 72));

        sdtNV.setForeground(new java.awt.Color(0, 27, 72));

        jLabel6.setForeground(new java.awt.Color(0, 27, 72));
        jLabel6.setText("Số CMND");

        jLabel5.setForeground(new java.awt.Color(0, 27, 72));
        jLabel5.setText("Lương");

        add.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        add.setForeground(new java.awt.Color(0, 27, 72));
        add.setText("Thêm");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        maNV.setForeground(new java.awt.Color(0, 27, 72));

        soCMND.setForeground(new java.awt.Color(0, 27, 72));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 27, 72));
        jLabel8.setText("Thêm nhân viên");

        jScrollPane1.setForeground(new java.awt.Color(0, 27, 72));

        diachi.setColumns(20);
        diachi.setRows(5);
        jScrollPane1.setViewportView(diachi);

        gioitinh.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Nam", "Nữ" }));

        jLabel9.setText("Ngày sinh");

        ChucVu.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Phục vụ", "Quản lý", "Thu ngân" }));

        jLabel10.setText("Chức vụ");

        jLabel11.setText("Ca phục vụ");

        Ca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PartTime", "FullTime" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(62, 62, 62)
                                        .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel7))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(Ca, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(44, 44, 44)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(sdtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(luong, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(soCMND, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(8, 8, 8)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(maNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(soCMND, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenNV, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(gioitinh, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sdtNV, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ngaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Ca, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(luong, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        // TODO add your handling code here:
       if (add.getText().equals("Cập nhật")) {
            if (getCMND().equals("") || getCMND().length() < 9) {
                JOptionPane.showMessageDialog(this, "CMND không được để trống và phải đủ 9 số !!!");
            } else if (getTenNV().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập tên Nhân viên !!!");
            } else if (getSDT().equals("") || getSDT().length() != 10) {
                JOptionPane.showMessageDialog(this, "SĐT không được để trống và phải có đủ 10 số !!!");
            } else if (getNgaySinh().equals("") || getNgaySinh().length() != 10) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh theo định dạng dd-MM-yyyy!!!");
            } else if (getDiaChi().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ !!!");
            } else if (getLuong().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập lương !!!");
            } else {

                SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss dd-MM-yyyy");
                Date date = new Date(System.currentTimeMillis());
                
                int male = gioitinh.getSelectedIndex();
                boolean sqlgioitinh = false;
                if (male == 1) {
                    sqlgioitinh = true;
                }
                String loainhanvienn = "PartTime";
                int k = Ca.getSelectedIndex();
                boolean sqlk = false;
                if (k == 1) {
                    sqlk = true;
                }
                int chucvu = ChucVu.getSelectedIndex();
                String sqlchucvu = "";
                if (chucvu == 0) {
                    sqlchucvu = "Phục vụ";
                } else if (chucvu == 1) {
                    sqlchucvu = "Quản lý";
                } else {
                    sqlchucvu = "Thu ngân";
                }
                try {
                    String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
                    Connection conn = DriverManager.getConnection(dbURL);
                    Statement statement = conn.createStatement();
                    if (conn != null) {
                        System.out.println("Connected");
                        DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                        
                        
                        String datetostring =ngaysinh.getText();
                        String[] spilitstringdate = datetostring.split("/");
                        datetostring=spilitstringdate[2]+"-"+spilitstringdate[1]+"-"+spilitstringdate[0];
                        
                        //String sqlUpdate = "UPDATE NHANVIEN SET DIACHI = 'Hanoi', LUONG = 10000.00;";
                       // String query = " insert into NHANVIEN (tenNV,sdt,ngaysinh,diachi,gioitinh,CMND,loaiNV,chucvu,luong,ngayvaolam) values (N'" + getTenNV() + "','" + getSDT() + "','" + ngaysinh.getText() + "',N'" + getDiaChi() + "',N'" + sqlgioitinh + "','" + getCMND() + "','" + sqlk + "',N'" + sqlchucvu + "','" + getLuong() + "','" + date + "')";
                        // xét tài khoản ko dc trùng
                        String updatequery="update NHANVIEN " 
					+ "set tenNV = N'" + getTenNV() + "'"
                                        + ",sdt = '" + getSDT() + "'"
                                        + ",ngaysinh = '" + datetostring + "'"
                                        + ",diachi = N'" + getDiaChi() + "'"
                                        + ",gioitinh = N'" + sqlgioitinh + "'"
                                        + ",CMND = '" + getCMND() + "'"
					+ ",loaiNV= N'" + sqlk + "'"
					+ ",chucvu = N'" + sqlchucvu + "'"
					+ ",luong = '" + getLuong() + "'"
              //                          + ",ngayvaolam = '" +  + "'"
					+ "where idNV = '" + Integer.parseInt(maNV.getText()) + "'";
                        System.out.println(Integer.parseInt(maNV.getText()));
                        boolean kiemtrathemnhanvien;
                        kiemtrathemnhanvien = statement.execute(updatequery);
                        if (kiemtrathemnhanvien == false) {
                            JOptionPane.showMessageDialog(this, "Cập nhật thành công !!!");
                            this.dispose();
                            quanlynhanvien.loadTable();
                        }
                    }
                } catch (SQLException ex) {
                    System.err.println("Cannot connect database, " + ex);
                } 
            }
        } else
        {
        String getchar = getNgaySinh();
        String getcharngaysinh = ""+getchar.charAt(2);
        if (getCMND().equals("") || getCMND().length() != 9) {
            JOptionPane.showMessageDialog(this, "CMND không được để trống và phải đủ 9 số !!!");
        } else if (getTenNV().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập tên Nhân viên !!!");
        } else if (getSDT().equals("") || getSDT().length() != 10) {
            JOptionPane.showMessageDialog(this, "SĐT không được để trống và phải có đủ 10 số !!!");
        } else if (getNgaySinh().equals("") || getNgaySinh().length() != 10 || !getcharngaysinh.equals("/")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập ngày sinh theo định dạng vd: 05/05/1999 !!!");
        } else if (getDiaChi().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập địa chỉ !!!");
        } else if (getLuong().equals("")) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập lương !!!");
        } else {

            SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
            Date date = new Date(System.currentTimeMillis());
            
            String datetostring =ngaysinh.getText();
            String[] spilitstringdate = datetostring.split("/");
            datetostring=spilitstringdate[2]+"-"+spilitstringdate[1]+"-"+spilitstringdate[0];
            
            
            int male = gioitinh.getSelectedIndex();
            boolean sqlgioitinh = false;
            if (male == 1) {
                sqlgioitinh = true;
            }
            String loainhanvienn = "PartTime";
            int k = Ca.getSelectedIndex();
            boolean sqlk = false;
            if (k == 1) {
                sqlk = true;
            }
            int chucvu = ChucVu.getSelectedIndex();
            String sqlchucvu = "";
            if (chucvu == 0) {
                sqlchucvu = "Phục vụ";
            } else if (chucvu == 1) {
                sqlchucvu = "Quản lý";
            } else {
                sqlchucvu = "Thu ngân";
            }
            try {
                String dbURL = "jdbc:sqlserver://localhost;databaseName=QL_NHA_HANG;user=sa;password=sa";
                Connection conn = DriverManager.getConnection(dbURL);
                Statement statement = conn.createStatement();
                if (conn != null) {
                    System.out.println("Connected");
                    DatabaseMetaData dm = (DatabaseMetaData) conn.getMetaData();
                    //String sqlUpdate = "UPDATE NHANVIEN SET DIACHI = 'Hanoi', LUONG = 10000.00;";
                    String query = " insert into NHANVIEN (tenNV,sdt,ngaysinh,diachi,gioitinh,CMND,loaiNV,chucvu,luong,ngayvaolam) values (N'" + getTenNV() + "','" + getSDT() + "','" + datetostring + "',N'" + getDiaChi() + "',N'" + sqlgioitinh + "','" + getCMND() + "','" + sqlk + "',N'" + sqlchucvu + "','" + getLuong() + "','" + date + "')";
                    // xét tài khoản ko dc trùng
                    boolean kiemtrathemnhanvien;
                    kiemtrathemnhanvien = statement.execute(query);
                    if (kiemtrathemnhanvien == false) {
                        JOptionPane.showMessageDialog(this, "Thêm nhân viên thành công !!!");
                        this.dispose();
                        quanlynhanvien.loadTable();
                    }
                }
            } catch (SQLException ex) {
                System.err.println("Cannot connect database, " + ex);
            }
        }
        }

    }//GEN-LAST:event_addActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    /**
     * @param args the command line arguments
     * @return
     */
    public String getTenNV() {
        return tenNV.getText();
    }

    public String getCMND() {
        return soCMND.getText();
    }

    public String getSDT() {
        return sdtNV.getText();
    }

    public String getNgaySinh() {
        return ngaysinh.getText();
    }

    public int getGioiTinh() {
        return gioitinh.getSelectedIndex();
    }

    public String getDiaChi() {
        return diachi.getText();
    }

    public String getLuong() {
        return luong.getText();
    }

    public void setTextName(String str) {
        tenNV.setText(str);
    }

    public void setTextSDT(String str) {
        sdtNV.setText(str);
    }

    public void setGioiTinh(int str) {
        gioitinh.setSelectedIndex(str);
    }

    public void setDiaChi(String str) {
        diachi.setText(str);
    }

    public void setLuong(String str) {
        luong.setText(str);
    }

    public void setCMND(String str) {
        soCMND.setText(str);
    }

    public void setNgaySinh(String str) {
        ngaysinh.setText(str);
    }

    public void setTextjlabel8(String str) {
        jLabel8.setText(str);
    }

    public void setTextjbtadd(String str) {
        add.setText(str);
    }

    public String getTextjlabel8() {
        return jLabel8.getText();
    }

    public String getTextjbtadd() {
        return add.getText();
    }

    public void setChucVu(int i) {
        ChucVu.setSelectedIndex(i);
    }

    public void setCa(int i) {
        Ca.setSelectedIndex(i);
    }

    public void setTextmaNV(String str) {
        maNV.setText(str);
    }

    public void hidemaNV() {
        maNV.setEditable(false);
        maNV.setEnabled(false);
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(themmoinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(themmoinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(themmoinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(themmoinv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new themmoinv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Ca;
    private javax.swing.JComboBox ChucVu;
    private javax.swing.JButton add;
    private javax.swing.JButton cancel;
    private javax.swing.JTextArea diachi;
    private javax.swing.JComboBox gioitinh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField luong;
    private javax.swing.JTextField maNV;
    private javax.swing.JTextField ngaysinh;
    private javax.swing.JTextField sdtNV;
    private javax.swing.JTextField soCMND;
    private javax.swing.JTextField tenNV;
    // End of variables declaration//GEN-END:variables
}
