/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pmphanlop;

import BUS.QLTour;
import DAO.DAO;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.*;

/**
 *
 * @author tattr
 */
public class DSTour extends javax.swing.JFrame {

    /**
     * Creates new form DSTour
     */
    QLTour qltour = new QLTour();
    
    
    public DSTour() {
        initComponents();
        TourTable.setModel(qltour.getDSTour(TourTable));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TourTable = new javax.swing.JTable();
        AddTourBtn = new javax.swing.JButton();
        DeleteTourBtn = new javax.swing.JButton();
        UpdateTourBtn = new javax.swing.JButton();
        SearchTextf = new javax.swing.JTextField();
        SearchLabel = new javax.swing.JButton();
        SortComboBox = new javax.swing.JComboBox<>();
        SortLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Danh sách Tour");

        TourTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã Tour", "Tên Tour", "Thời gian tour", "Ngày khởi hành", "Giá"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TourTable);
        if (TourTable.getColumnModel().getColumnCount() > 0) {
            TourTable.getColumnModel().getColumn(0).setMinWidth(80);
            TourTable.getColumnModel().getColumn(0).setMaxWidth(80);
            TourTable.getColumnModel().getColumn(1).setMinWidth(350);
            TourTable.getColumnModel().getColumn(1).setMaxWidth(350);
            TourTable.getColumnModel().getColumn(3).setMinWidth(180);
            TourTable.getColumnModel().getColumn(3).setMaxWidth(180);
            TourTable.getColumnModel().getColumn(4).setMinWidth(100);
            TourTable.getColumnModel().getColumn(4).setMaxWidth(100);
        }

        AddTourBtn.setText("Thêm");
        AddTourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTourBtnActionPerformed(evt);
            }
        });

        DeleteTourBtn.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        DeleteTourBtn.setText("Xóa");
        DeleteTourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteTourBtnActionPerformed(evt);
            }
        });

        UpdateTourBtn.setText("Sửa");
        UpdateTourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateTourBtnActionPerformed(evt);
            }
        });

        SearchTextf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTextfActionPerformed(evt);
            }
        });

        SearchLabel.setText("Tìm kiếm");
        SearchLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLabelActionPerformed(evt);
            }
        });

        SortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tăng theo giá", "Giảm theo giá", "Ngày khởi hành gần nhất" }));
        SortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortComboBoxActionPerformed(evt);
            }
        });

        SortLabel.setText("Sắp xếp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SearchLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchTextf, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(244, 244, 244)
                        .addComponent(SortLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(DeleteTourBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(UpdateTourBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(AddTourBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SearchTextf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchLabel)
                    .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortLabel))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(AddTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(DeleteTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(UpdateTourBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 511, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddTourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTourBtnActionPerformed
        // TODO add your handling code here:
        AddTour a = new AddTour();
        a.setVisible(true);
    }//GEN-LAST:event_AddTourBtnActionPerformed

    private void SearchTextfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTextfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTextfActionPerformed

    private void SortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortComboBoxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_SortComboBoxActionPerformed

    private void SearchLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchLabelActionPerformed

    private void UpdateTourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateTourBtnActionPerformed
        // TODO add your handling code here:
        UpdateTour a = new UpdateTour();
        a.setVisible(true);
    }//GEN-LAST:event_UpdateTourBtnActionPerformed

    private void DeleteTourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteTourBtnActionPerformed
        // TODO add your handling code here:
        int row = TourTable.getSelectedRow();
        int id = (int) TourTable.getModel().getValueAt(row, 0);
        DAO.delete("tour", id+"");
//        TourTable.remove(row);
    }//GEN-LAST:event_DeleteTourBtnActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DSTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DSTour().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTourBtn;
    private javax.swing.JButton DeleteTourBtn;
    private javax.swing.JButton SearchLabel;
    private javax.swing.JTextField SearchTextf;
    private javax.swing.JComboBox<String> SortComboBox;
    private javax.swing.JLabel SortLabel;
    private javax.swing.JTable TourTable;
    private javax.swing.JButton UpdateTourBtn;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
